import { useState } from 'react'
import { Navigate } from 'react-router-dom'
import { ArrowLeft, KeyRound, Sparkles } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
export default function AuthPage() {
  const { user, signIn, signUp, resetPassword, configured } = useAuth(); const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  if (user) return <Navigate to="/" replace />
  const update = event => setForm({ ...form, [event.target.name]: event.target.value })
  const submit = async event => { event.preventDefault(); setMessage(''); setBusy(true); try { if (mode === 'login') await signIn(form); if (mode === 'register') { await signUp(form); setMessage('Revisa tu correo para confirmar tu cuenta.') } if (mode === 'reset') { await resetPassword(form.email); setMessage('Te enviamos un enlace para restablecer tu contraseña.') } } catch (error) { setMessage(error.message || 'No pudimos completar la acción.') } finally { setBusy(false) } }
  return <main className="auth-page"><section className="auth-copy"><div className="auth-logo"><span>m</span>MinDoku</div><p className="eyebrow">JUEGA. PROGRESA. DOMINA.</p><h1>Tu próxima<br/><em>victoria</em> empieza aquí.</h1><p>Sudokus ilimitados, progreso real y desafíos hechos para mantener tu mente en forma.</p><Sparkles className="auth-spark" /></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><div className="auth-tabs">{mode !== 'reset' && <><button type="button" className={mode === 'login' ? 'selected' : ''} onClick={() => setMode('login')}>Entrar</button><button type="button" className={mode === 'register' ? 'selected' : ''} onClick={() => setMode('register')}>Crear cuenta</button></>}</div><h2>{mode === 'login' ? 'Qué bueno verte' : mode === 'register' ? 'Crea tu perfil' : 'Recupera tu acceso'}</h2><p>{mode === 'reset' ? 'Te enviaremos un enlace seguro a tu correo.' : 'Continúa tu aventura en MinDoku.'}</p>{!configured && <p className="auth-error">Faltan las variables de Supabase en Vercel.</p>}{mode === 'register' && <label>Nombre<input name="name" value={form.name} onChange={update} required placeholder="Tu nombre" /></label>}<label>Correo electrónico<input type="email" name="email" value={form.email} onChange={update} required placeholder="Ingresa tu correo electrónico" /></label>{mode !== 'reset' && <label>Contraseña<input type="password" name="password" value={form.password} onChange={update} required minLength="6" placeholder="Contraseña" /></label>}<button className="auth-submit" disabled={busy || !configured}>{busy ? 'Un momento...' : mode === 'login' ? 'Entrar a MinDoku' : mode === 'register' ? 'Crear mi cuenta' : 'Enviar enlace'}</button>{mode === 'login' && <button className="text-action" type="button" onClick={() => setMode('reset')}><KeyRound size={16}/> Olvidé mi contraseña</button>}{mode === 'reset' && <button className="text-action" type="button" onClick={() => setMode('login')}><ArrowLeft size={16}/> Volver a entrar</button>}{message && <p className="auth-message">{message}</p>}</form></section></main>
}
