import { useEffect, useMemo, useState } from 'react'
import { Heart, Lightbulb, Pause, RotateCcw, ShieldCheck } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import SudokuBoard from '../components/SudokuBoard'
import NumberPad from '../components/NumberPad'
import { createPuzzle } from '../utils/sudoku'
import { useGame } from '../context/GameContext'
const labels={easy:'Fácil',intermediate:'Intermedio',hard:'Difícil',master:'Maestro'}
export default function GamePage({daily}) { const {difficulty='easy'}=useParams(), nav=useNavigate(), {recordWin,spend}=useGame(); const [game,setGame]=useState(()=>createPuzzle(daily?'hard':difficulty)); const [board,setBoard]=useState(game.puzzle.map(r=>[...r])); const [selected,setSelected]=useState(null); const [lives,setLives]=useState(3),[seconds,setSeconds]=useState(0),[paused,setPaused]=useState(false),[notesMode,setNotesMode]=useState(false),[notes,setNotes]=useState({}),[finished,setFinished]=useState(false),[won,setWon]=useState(false),[hintsUsed,setHintsUsed]=useState(0)
 const givens=game.puzzle; useEffect(()=>{if(paused||finished)return;const i=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(i)},[paused,finished]); const time=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`
 const reset=()=>{const next=createPuzzle(daily?'hard':difficulty);setGame(next);setBoard(next.puzzle.map(r=>[...r]));setLives(3);setSeconds(0);setNotes({});setHintsUsed(0);setFinished(false);setWon(false)}
 const enter=n=>{if(!selected||givens[selected.r][selected.c]||finished)return;const k=`${selected.r}-${selected.c}`;if(notesMode){setNotes(p=>({...p,[k]:p[k]?.includes(n)?p[k].filter(x=>x!==n):[...(p[k]||[]),n]}));return} if(n!==game.solution[selected.r][selected.c]){const l=lives-1;setLives(l);if(!l)setFinished(true);return} const next=board.map(r=>[...r]);next[selected.r][selected.c]=n;setBoard(next);setNotes(p=>({...p,[k]:[]}));if(next.flat().every(Boolean)){const coins=daily?100:({easy:20,intermediate:40,hard:70,master:120}[difficulty]);setWon(true);setFinished(true);recordWin({coins,xp:daily?200:100,seconds,difficulty:daily?'hard':difficulty,mistakes:3-lives,hintsUsed,daily})}}
 const erase=()=>{if(selected&&!givens[selected.r][selected.c]){const n=board.map(r=>[...r]);n[selected.r][selected.c]=0;setBoard(n)}}
 const hint=()=>{if(!selected||givens[selected.r][selected.c])return;if(spend(25)){const n=board.map(r=>[...r]);n[selected.r][selected.c]=game.solution[selected.r][selected.c];setBoard(n);setHintsUsed(value=>value+1)}}
 return <section className="game-page"><div className="game-top"><button className="back" onClick={()=>nav('/')}>← Salir</button><div><p className="eyebrow">{daily?'DESAFÍO DIARIO':'NUEVA PARTIDA'}</p><h2>{labels[daily?'hard':difficulty]}</h2></div><div className="game-status"><span className="timer">{time}</span><span className="lives">{[0,1,2].map(i=><Heart key={i} fill={i<lives?'currentColor':'none'}/>)}</span></div></div><div className="play-zone"><div><SudokuBoard board={board} givens={givens} selected={selected} onSelect={setSelected} notes={notes}/><NumberPad onNumber={enter} onErase={erase} disabled={paused||finished}/></div><div className="tools"><button onClick={()=>setPaused(!paused)}><Pause/> {paused?'Reanudar':'Pausar'}</button><button className={notesMode?'chosen':''} onClick={()=>setNotesMode(!notesMode)}>✎ Notas</button><button onClick={hint}><Lightbulb/> Pista <small>25 ●</small></button><button onClick={reset}><RotateCcw/> Reiniciar</button><button><ShieldCheck/> Comprobar</button></div></div>{finished&&<div className="modal"><div className="modal-card"><span>{won?'✦':'♡'}</span><h2>{won?'¡Tablero completado!':'Game over'}</h2><p>{won?'Tu mente está en forma.':'Has agotado tus tres vidas.'}</p><div className="result"><b>{time}<small>tiempo</small></b><b>{3-lives}<small>errores</small></b><b>+{won?(daily?100:20):0}<small>monedas</small></b></div>{!won&&!lives?<button className="primary-button" onClick={()=>spend(100)&&setLives(1)}>Continuar · 100 ●</button>:null}<button className="secondary-button" onClick={reset}>Nuevo Sudoku</button></div></div>}</section> }
