import { Crown, Medal, Timer, Trophy } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useAuth } from '../context/AuthContext'
import { supabase } from '../services/supabase'
const time = seconds => Number.isInteger(seconds) ? `${String(Math.floor(seconds / 60)).padStart(2,'0')}:${String(seconds % 60).padStart(2,'0')}` : '—'
export default function RankingPage(){
  const { user }=useAuth(); const [players,setPlayers]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(()=>{let alive=true; async function load(){const {data,error}=await supabase.from('profiles').select('id,name,avatar,level,solved,best_time_seconds').order('level',{ascending:false}).order('solved',{ascending:false}).order('best_time_seconds',{ascending:true,nullsFirst:false}).limit(100);if(!alive)return;if(error)setError('No se pudo cargar el ranking todavía.');else setPlayers(data||[]);setLoading(false)}load();return()=>{alive=false}},[])
  return <section className="module-page"><div className="module-hero"><div><p className="eyebrow">COMUNIDAD MINDOKU</p><h1>Ranking global</h1><p>Los jugadores que más han entrenado su mente.</p></div><Trophy/></div><div className="ranking-table"><div className="ranking-head"><span>Posición</span><span>Jugador</span><span>Nivel</span><span>Sudokus</span><span>Mejor tiempo</span></div>{loading&&<p className="ranking-state">Cargando jugadores...</p>}{error&&<p className="ranking-state">{error}</p>}{!loading&&!error&&!players.length&&<p className="ranking-state">Aún no hay jugadores en el ranking.</p>}{players.map((row,index)=><article key={row.id} className={row.id===user?.id?'you':''}><span className="rank-icon">{index===0?<Crown/>:index<3?<Medal/>:`#${index+1}`}</span><strong>{row.name||'Jugador'}{row.id===user?.id&&<small>Tú</small>}</strong><span>{row.level}</span><span>{row.solved}</span><span><Timer size={15}/>{time(row.best_time_seconds)}</span></article>)}</div></section>}
