const range = Array.from({ length: 9 }, (_, i) => i)
const seeded = seed => { let value = [...String(seed)].reduce((n, char) => (n * 31 + char.charCodeAt(0)) >>> 0, 2166136261); return () => { value = (value * 1664525 + 1013904223) >>> 0; return value / 4294967296 } }
const shuffle = (array, random = Math.random) => { const list = [...array]; for (let i = list.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [list[i], list[j]] = [list[j], list[i]] } return list }
export function valid(board, row, col, value) { for (let i = 0; i < 9; i++) if (board[row][i] === value || board[i][col] === value) return false; const r = row - row % 3, c = col - col % 3; for (let y = r; y < r + 3; y++) for (let x = c; x < c + 3; x++) if (board[y][x] === value) return false; return true }
function solve(board, random) { for (const r of range) for (const c of range) if (!board[r][c]) { for (const n of shuffle(range.map(x => x + 1), random)) if (valid(board, r, c, n)) { board[r][c] = n; if (solve(board, random)) return true; board[r][c] = 0 } return false }; return true }
function countSolutions(board, count = 0) { for (const r of range) for (const c of range) if (!board[r][c]) { for (let n = 1; n <= 9; n++) if (valid(board, r, c, n)) { board[r][c] = n; count = countSolutions(board, count); board[r][c] = 0; if (count > 1) return count } return count }; return count + 1 }
const clues = { easy: 42, intermediate: 35, hard: 29, master: 24 }
export function createPuzzle(difficulty = 'easy', seed) { const random = seed ? seeded(seed) : Math.random; const solution = Array.from({ length: 9 }, () => Array(9).fill(0)); solve(solution, random); const puzzle = solution.map(row => [...row]); const cells = shuffle(range.flatMap(r => range.map(c => [r, c])), random); let remaining = 81; for (const [r, c] of cells) { if (remaining <= clues[difficulty]) break; const hold = puzzle[r][c]; puzzle[r][c] = 0; if (countSolutions(puzzle.map(x => [...x])) !== 1) puzzle[r][c] = hold; else remaining-- } return { puzzle, solution } }
export const dailySeed = (difficulty, date = new Date()) => `${date.toISOString().slice(0, 10)}-${difficulty}-mindoku`
